export const countries = [
  { code: 'US', name: 'Estados Unidos', name_en: 'United States', dial_code: '+1', digits: 10 },
  { code: 'MA', name: 'Marruecos', name_en: 'Morocco', dial_code: '+212', digits: 9 },
  { code: 'ES', name: 'España', name_en: 'Spain', dial_code: '+34', digits: 9 },
  { code: 'FR', name: 'Francia', name_en: 'France', dial_code: '+33', digits: 9 },
  { code: 'DE', name: 'Alemania', name_en: 'Germany', dial_code: '+49', digits: 10 },
  { code: 'IT', name: 'Italia', name_en: 'Italy', dial_code: '+39', digits: 10 },
  { code: 'GB', name: 'Reino Unido', name_en: 'United Kingdom', dial_code: '+44', digits: 10 },
  { code: 'PT', name: 'Portugal', name_en: 'Portugal', dial_code: '+351', digits: 9 },
  { code: 'NL', name: 'Países Bajos', name_en: 'Netherlands', dial_code: '+31', digits: 9 },
  { code: 'BE', name: 'Bélgica', name_en: 'Belgium', dial_code: '+32', digits: 9 },
  { code: 'CH', name: 'Suiza', name_en: 'Switzerland', dial_code: '+41', digits: 9 },
  { code: 'AT', name: 'Austria', name_en: 'Austria', dial_code: '+43', digits: 10 },
  { code: 'SE', name: 'Suecia', name_en: 'Sweden', dial_code: '+46', digits: 9 },
  { code: 'NO', name: 'Noruega', name_en: 'Norway', dial_code: '+47', digits: 8 },
  { code: 'FI', name: 'Finlandia', name_en: 'Finland', dial_code: '+358', digits: 9 },
  { code: 'DK', name: 'Dinamarca', name_en: 'Denmark', dial_code: '+45', digits: 8 },
  { code: 'PL', name: 'Polonia', name_en: 'Poland', dial_code: '+48', digits: 9 },
  { code: 'CZ', name: 'República Checa', name_en: 'Czech Republic', dial_code: '+420', digits: 9 },
  { code: 'HU', name: 'Hungría', name_en: 'Hungary', dial_code: '+36', digits: 9 },
  { code: 'GR', name: 'Grecia', name_en: 'Greece', dial_code: '+30', digits: 10 },
  { code: 'IE', name: 'Irlanda', name_en: 'Ireland', dial_code: '+353', digits: 9 },
  { code: 'RO', name: 'Rumanía', name_en: 'Romania', dial_code: '+40', digits: 9 },
  { code: 'BG', name: 'Bulgaria', name_en: 'Bulgaria', dial_code: '+359', digits: 9 },
  { code: 'HR', name: 'Croacia', name_en: 'Croatia', dial_code: '+385', digits: 9 },
  { code: 'SI', name: 'Eslovenia', name_en: 'Slovenia', dial_code: '+386', digits: 8 },
  { code: 'SK', name: 'Eslovaquia', name_en: 'Slovakia', dial_code: '+421', digits: 9 },
  { code: 'LT', name: 'Lituania', name_en: 'Lithuania', dial_code: '+370', digits: 8 },
  { code: 'LV', name: 'Letonia', name_en: 'Latvia', dial_code: '+371', digits: 8 },
  { code: 'EE', name: 'Estonia', name_en: 'Estonia', dial_code: '+372', digits: 8 },
  { code: 'MT', name: 'Malta', name_en: 'Malta', dial_code: '+356', digits: 8 },
  { code: 'CY', name: 'Chipre', name_en: 'Cyprus', dial_code: '+357', digits: 8 },
  { code: 'LU', name: 'Luxemburgo', name_en: 'Luxembourg', dial_code: '+352', digits: 9 },
  { code: 'IS', name: 'Islandia', name_en: 'Iceland', dial_code: '+354', digits: 7 },
  { code: 'AL', name: 'Albania', name_en: 'Albania', dial_code: '+355', digits: 9 },
  { code: 'MK', name: 'Macedonia del Norte', name_en: 'North Macedonia', dial_code: '+389', digits: 8 },
  { code: 'RS', name: 'Serbia', name_en: 'Serbia', dial_code: '+381', digits: 9 },
  { code: 'ME', name: 'Montenegro', name_en: 'Montenegro', dial_code: '+382', digits: 8 },
  { code: 'BA', name: 'Bosnia y Herzegovina', name_en: 'Bosnia and Herzegovina', dial_code: '+387', digits: 8 },
  { code: 'XK', name: 'Kosovo', name_en: 'Kosovo', dial_code: '+383', digits: 8 },
  { code: 'MD', name: 'Moldavia', name_en: 'Moldova', dial_code: '+373', digits: 8 },
  { code: 'UA', name: 'Ucrania', name_en: 'Ukraine', dial_code: '+380', digits: 9 },
  { code: 'BY', name: 'Bielorrusia', name_en: 'Belarus', dial_code: '+375', digits: 9 },
  { code: 'GE', name: 'Georgia', name_en: 'Georgia', dial_code: '+995', digits: 9 },
  { code: 'AM', name: 'Armenia', name_en: 'Armenia', dial_code: '+374', digits: 8 },
  { code: 'AZ', name: 'Azerbaiyán', name_en: 'Azerbaijan', dial_code: '+994', digits: 9 },
  { code: 'TR', name: 'Turquía', name_en: 'Turkey', dial_code: '+90', digits: 10 },
  { code: 'IL', name: 'Israel', name_en: 'Israel', dial_code: '+972', digits: 9 },
  { code: 'JO', name: 'Jordania', name_en: 'Jordan', dial_code: '+962', digits: 9 },
  { code: 'LB', name: 'Líbano', name_en: 'Lebanon', dial_code: '+961', digits: 8 },
  { code: 'SA', name: 'Arabia Saudita', name_en: 'Saudi Arabia', dial_code: '+966', digits: 9 },
  { code: 'AE', name: 'Emiratos Árabes Unidos', name_en: 'United Arab Emirates', dial_code: '+971', digits: 9 },
  { code: 'QA', name: 'Qatar', name_en: 'Qatar', dial_code: '+974', digits: 8 },
  { code: 'KW', name: 'Kuwait', name_en: 'Kuwait', dial_code: '+965', digits: 8 },
  { code: 'BH', name: 'Bahréin', name_en: 'Bahrain', dial_code: '+973', digits: 8 },
  { code: 'OM', name: 'Omán', name_en: 'Oman', dial_code: '+968', digits: 8 },
  { code: 'YE', name: 'Yemen', name_en: 'Yemen', dial_code: '+967', digits: 9 },
  { code: 'IQ', name: 'Irak', name_en: 'Iraq', dial_code: '+964', digits: 10 },
  { code: 'SY', name: 'Siria', name_en: 'Syria', dial_code: '+963', digits: 9 },
  { code: 'PS', name: 'Palestina', name_en: 'Palestine', dial_code: '+970', digits: 9 },
  { code: 'EG', name: 'Egipto', name_en: 'Egypt', dial_code: '+20', digits: 10 },
  { code: 'LY', name: 'Libia', name_en: 'Libya', dial_code: '+218', digits: 9 },
  { code: 'TN', name: 'Túnez', name_en: 'Tunisia', dial_code: '+216', digits: 8 },
  { code: 'DZ', name: 'Argelia', name_en: 'Algeria', dial_code: '+213', digits: 9 },
  { code: 'MR', name: 'Mauritania', name_en: 'Mauritania', dial_code: '+222', digits: 8 },
  { code: 'ML', name: 'Mali', name_en: 'Mali', dial_code: '+223', digits: 8 },
  { code: 'SN', name: 'Senegal', name_en: 'Senegal', dial_code: '+221', digits: 9 },
  { code: 'GN', name: 'Guinea', name_en: 'Guinea', dial_code: '+224', digits: 9 },
  { code: 'CI', name: 'Costa de Marfil', name_en: 'Ivory Coast', dial_code: '+225', digits: 8 },
  { code: 'BF', name: 'Burkina Faso', name_en: 'Burkina Faso', dial_code: '+226', digits: 8 },
  { code: 'NE', name: 'Níger', name_en: 'Niger', dial_code: '+227', digits: 8 },
  { code: 'TG', name: 'Togo', name_en: 'Togo', dial_code: '+228', digits: 8 },
  { code: 'BJ', name: 'Benín', name_en: 'Benin', dial_code: '+229', digits: 8 },
  { code: 'NG', name: 'Nigeria', name_en: 'Nigeria', dial_code: '+234', digits: 10 },
  { code: 'CM', name: 'Camerún', name_en: 'Cameroon', dial_code: '+237', digits: 9 },
  { code: 'TD', name: 'Chad', name_en: 'Chad', dial_code: '+235', digits: 8 },
  { code: 'CF', name: 'República Centroafricana', name_en: 'Central African Republic', dial_code: '+236', digits: 8 },
  { code: 'GA', name: 'Gabón', name_en: 'Gabon', dial_code: '+241', digits: 8 },
  { code: 'CG', name: 'Congo', name_en: 'Congo', dial_code: '+242', digits: 9 },
  { code: 'CD', name: 'República Democrática del Congo', name_en: 'Democratic Republic of the Congo', dial_code: '+243', digits: 9 },
  { code: 'AO', name: 'Angola', name_en: 'Angola', dial_code: '+244', digits: 9 },
  { code: 'GW', name: 'Guinea-Bisáu', name_en: 'Guinea-Bissau', dial_code: '+245', digits: 7 },
  { code: 'ST', name: 'Santo Tomé y Príncipe', name_en: 'Sao Tome and Principe', dial_code: '+239', digits: 7 },
  { code: 'GQ', name: 'Guinea Ecuatorial', name_en: 'Equatorial Guinea', dial_code: '+240', digits: 9 },
  { code: 'ZM', name: 'Zambia', name_en: 'Zambia', dial_code: '+260', digits: 9 },
  { code: 'MW', name: 'Malaui', name_en: 'Malawi', dial_code: '+265', digits: 9 },
  { code: 'MZ', name: 'Mozambique', name_en: 'Mozambique', dial_code: '+258', digits: 9 },
  { code: 'ZW', name: 'Zimbabue', name_en: 'Zimbabwe', dial_code: '+263', digits: 9 },
  { code: 'NA', name: 'Namibia', name_en: 'Namibia', dial_code: '+264', digits: 9 },
  { code: 'BW', name: 'Botsuana', name_en: 'Botswana', dial_code: '+267', digits: 8 },
  { code: 'LS', name: 'Lesoto', name_en: 'Lesotho', dial_code: '+266', digits: 8 },
  { code: 'SZ', name: 'Esuatini', name_en: 'Eswatini', dial_code: '+268', digits: 8 },
  { code: 'KM', name: 'Comoras', name_en: 'Comoros', dial_code: '+269', digits: 7 },
  { code: 'MU', name: 'Mauricio', name_en: 'Mauritius', dial_code: '+230', digits: 7 },
  { code: 'SC', name: 'Seychelles', name_en: 'Seychelles', dial_code: '+248', digits: 7 },
  { code: 'RE', name: 'Reunión', name_en: 'Reunion', dial_code: '+262', digits: 9 },
  { code: 'YT', name: 'Mayotte', name_en: 'Mayotte', dial_code: '+262', digits: 9 },
  { code: 'TF', name: 'Territorios Australes Franceses', name_en: 'French Southern Territories', dial_code: '+262', digits: 9 },
];